# This file was generated by GoReleaser. DO NOT EDIT.
cask "dpilot" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "0067c03510372d7a9ad701e1300b827316dcea4526f5c1f794edee2c0f77258e"
      url "https://github.com/haraldpdl/dpilot/releases/download/v#{version}/dpilot_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c61f91236101d82b34880f3bfcf816b05b6cd40829fa92ad8ccb42d60e753096"
      url "https://github.com/haraldpdl/dpilot/releases/download/v#{version}/dpilot_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a906746402f722d79650347bab1daa670a9f424304b13ed6802f4cf6d1abf158"
      url "https://github.com/haraldpdl/dpilot/releases/download/v#{version}/dpilot_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d47ae3dce04032bc9635c3d3192b67bd169af3a9fbd6028a7132a997395095d5"
      url "https://github.com/haraldpdl/dpilot/releases/download/v#{version}/dpilot_linux_arm64.tar.gz"
    end
  end

  name "dpilot"
  desc "Orchestrate ordered groups of ddev projects"
  homepage "https://github.com/haraldpdl/dpilot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dpilot"

  # No zap stanza required

end
