# This file was generated by GoReleaser. DO NOT EDIT.
cask "dpilot" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "2e8f1b0596ff8347355dc2d8418172dc4877bbb68af3fe8a2f654ece1c419f49"
      url "https://github.com/haraldpdl/dpilot/releases/download/v#{version}/dpilot_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3861a266d7ee9fc4c9ac5e1d041761b8888848643f2241ba0cef3c0e999ef76"
      url "https://github.com/haraldpdl/dpilot/releases/download/v#{version}/dpilot_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "69c6fb55abaa8a55517dcdeb225cab4152be4a986351db076ab9929a21db3c5e"
      url "https://github.com/haraldpdl/dpilot/releases/download/v#{version}/dpilot_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "48cb1d76da119b6dbc28dc8a0013000cc03cc87d63f607ba560d4e2e6039f5c6"
      url "https://github.com/haraldpdl/dpilot/releases/download/v#{version}/dpilot_linux_arm64.tar.gz"
    end
  end

  name "dpilot"
  desc "Orchestrate ordered groups of ddev projects"
  homepage "https://github.com/haraldpdl/dpilot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dpilot"

  # No zap stanza required

end
