# This file was generated by GoReleaser. DO NOT EDIT.
cask "dpilot" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "e364457a42054d4707eba88eebbb256d5b9116146590aec66d76444dfdb82c4a"
      url "https://github.com/haraldpdl/dpilot/releases/download/v#{version}/dpilot_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f46dfd3aa3f6e05b30ddf17fcf09a9934f85f9f22f78812d50094224556c0697"
      url "https://github.com/haraldpdl/dpilot/releases/download/v#{version}/dpilot_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "71fe3e8cbf92f5807ae46ba8bbd5478ce1c4e616450df015b0b8af485a9ef135"
      url "https://github.com/haraldpdl/dpilot/releases/download/v#{version}/dpilot_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a57bf6a8509c37ef26419f258cce58fae6c29c8505c5766de153f1e2329330a0"
      url "https://github.com/haraldpdl/dpilot/releases/download/v#{version}/dpilot_linux_arm64.tar.gz"
    end
  end

  name "dpilot"
  desc "Orchestrate ordered groups of ddev projects"
  homepage "https://github.com/haraldpdl/dpilot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dpilot"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dpilot"]
    end
  end

  # No zap stanza required

end
