# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dpilot < Formula
  desc "Orchestrate ordered groups of ddev projects"
  homepage "https://github.com/haraldpdl/dpilot"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/haraldpdl/dpilot/releases/download/v0.1.1/dpilot_darwin_amd64.tar.gz"
      sha256 "12d75fe01ff9f24213453e4e1bb7d112c063d3692355f726cca3b16c2bb9d47e"

      define_method(:install) do
        bin.install "dpilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/haraldpdl/dpilot/releases/download/v0.1.1/dpilot_darwin_arm64.tar.gz"
      sha256 "1e275cfe73d7194fcc08e2bec82125d921ed1a79f25a9e6fd2e4a136dee592ab"

      define_method(:install) do
        bin.install "dpilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/haraldpdl/dpilot/releases/download/v0.1.1/dpilot_linux_amd64.tar.gz"
      sha256 "3c2e8e4107495a53aa173cd5728a2a476d7c6bebe4d24f0943cf2ba3d3d53939"
      define_method(:install) do
        bin.install "dpilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haraldpdl/dpilot/releases/download/v0.1.1/dpilot_linux_arm64.tar.gz"
      sha256 "0ffc509f9711ba4319fc738e3f19c7881df8385c6d80b5befb3d2a65dc3dcb90"
      define_method(:install) do
        bin.install "dpilot"
      end
    end
  end

  test do
    system "#{bin}/dpilot", "version"
  end
end
